apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rsglksrcx-go 
  janus-idp.io/tekton: rsglksrcx-go
  backstage.io/kubernetes-id: rsglksrcx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rsglksrcx-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  